### PR TITLE
Fixes 127 - ZonedDateTime in map keys can now be serialized with zone IDs

### LINKED ISSUE #127: ZonedDateTime in map keys ignores option to write Zone IDs
As of v2.9.9, the following fails:

```java
class Sample {
    private Map<ZonedDateTime, ZonedDateTime> map;
    private ZonedDateTime dateTime;

    public Sample() {
    }

    public ZonedDateTime getDateTime() {
        return dateTime;
    }

    public void setDateTime(ZonedDateTime dateTime) {
        this.dateTime = dateTime;
    }

    public Map<ZonedDateTime, ZonedDateTime> getMap() {
        return map;
    }

    public void setMap(Map<ZonedDateTime, ZonedDateTime> map) {
        this.map = map;
    }
}

public class JacksonTest {

    @Test
    public void shouldSerializeZoneIdInMapKeys() throws IOException {
        // given
        final ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new Jdk8Module());
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        objectMapper.enable(SerializationFeature.WRITE_DATES_WITH_ZONE_ID);

        final ZonedDateTime datetime = ZonedDateTime.parse("2007-12-03T10:15:30+01:00[Europe/Warsaw]");
        final HashMap<ZonedDateTime, ZonedDateTime> map = new HashMap<>();
        map.put(datetime, datetime);
        final Sample sample = new Sample();
        sample.setMap(map);
        sample.setDateTime(datetime);

        // when
        final String value = objectMapper.writeValueAsString(sample);

        // then
        assertThat(value).isEqualTo("{\"map\":" +
                "{\"2007-12-03T10:15:30+01:00[Europe/Warsaw]\":\"2007-12-03T10:15:30+01:00[Europe/Warsaw]\"}," +
                "\"dateTime\":\"2007-12-03T10:15:30+01:00[Europe/Warsaw]\"" +
                "}");
    }
}
```

I'd expect that Zone ID is written not only in map keys but also in map values. 
Currently `SerializationFeature.WRITE_DATES_WITH_ZONE_ID` has no impact on map keys.

Sample project:
[test.zip](https://github.com/FasterXML/jackson-modules-java8/files/3491978/test.zip)

### PR DESCRIPTION
**Pull request by vetler**
Fixes #127 - ZonedDateTime in map keys can now be serialized with zone IDs

### CODE REVIEW

File: datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java [hunk 1]
```diff
@@ -25,7 +26,11 @@ public void serialize(ZonedDateTime value, JsonGenerator gen, SerializerProvider
          *
          * Keeping timezone info is a new feature which needs to be implemented.
```
Comment (kupci) [inline datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java]: So now that it is implemented, the comment can be removed or changed, perhaps adding an @since?

Comment (kupci) [reply datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java]: And maybe a question for @cowtowncoder but should this go in 2.10.1 or 2.11, and then master?

**Comment by cowtowncoder** [comment]
Tough question on versioning. If we wanted to follow SemVer strictly, I think it should be included in 2.11 as there is behavioral change that might not be considered a bug (or it could be, hence ambiguity).
But 2.10.0 is just out -- if we had, say, 2.10.8, I'd say 2.11.

So: @kupci what do you think? I think I am ok with either 2.10.x or 2.11.

**Comment by cowtowncoder** [comment]
So: I think patch itself is fine. And the only process thing here is that unless I have already asked and received CLA:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

that would be needed now (just once; no need to file for more contributions)

Thank you @vetler (Kiitos!) for the contribution; looking forward to merging it once we figure out right branch.

**Comment by kupci** [comment]
Given this requires the `SerializationFeature.WRITE_DATES_WITH_ZONE_ID`, which it is now working via @vetler 's fix, **2.10.x** seems valid. In other words, this is a bug fix, so fits with 

> PATCH version when you make backwards compatible bug fixes.

**Comment by cowtowncoder** [comment]
Ok, then we'll go with 2.10.

File: datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java (hunk 1 above)
Comment (vetler) [reply datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java]: Changed the comment, not sure where I should add the `@since`... or just remove it entirely?

**Comment by vetler** [comment]
> So: I think patch itself is fine. And the only process thing here is that unless I have already asked and received CLA:
> 
> https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

Where do I send it?

**Comment by vetler** [comment]
Build failure seems unrelated to changes?

**Comment by kupci** [comment]
Yes, seems unrelated to changes. I wonder if there are still Sonatype issues, as this looks like the same error as previously with the 2.10 release. There's a ticket with Sonatype opened already.

> Checksum validation failed, expected 088cd9f174c370442f12200765610c3a98bfb69e but is ae19b6d3ac494b56b7134f261d60b6d7aa9e89d2 -> [Help 1]

**Comment by kupci** [comment]
And here's where to send the CLA (copying from another PR): 

> Simplest way is usually to print, fill & sign, scan, email to info at fasterxml dot com.

**Comment by cowtowncoder** [comment]
Sonatype fixed the problem with `jackson-annotations`, but it is possible to have a cached copy -- so it may make sense to `rm` either whole Maven cache, or at least:

    rm ~/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/

@vetler yes, send to `info` at fasterxml dot com

File: datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java (hunk 1 above)
Comment (kupci) [reply datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java]: Comment looks good to me.

Comment (cowtowncoder) [reply datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/key/ZonedDateTimeKeySerializer.java]: Ok to remove / not add `@since` in this case.

As I said, 2.10 is ok: so, either base off 2.10 and I can merge forward. Or change in `master` and I can cherry-pick back. Slightly easier first way (start with 2.10) but not a big deal.

**Comment by cowtowncoder** [comment]
CLA received, proceed with merging.
